### ISSUE TITLE
Clarification about license 

### ISSUE THREAD

**Issue by suprafun** [PerpetuumOnline/PerpetuumServer#6]
Hello, I would like to confirm that this project is under the MIT license ? I am interested in studying it very carefully so I can learn about writing my own MMO -style server backend for my own indie. project. This project seems quite amazing. I just want to clarify if I can use this repo. as source code to learn from towards my own closed source, commercial MMO -style server. Thank-you.

**Comment by Gargaj** [comment]
Yes: https://github.com/PerpetuumOnline/PerpetuumServer/blob/master/LICENSE

**Comment by suprafun** [comment]
Thank-you so very much.
